### ISSUE TITLE
Dependency on @hapi/joi is causing issues now that Joi has broken off of Hapi

### ISSUE THREAD

**Issue by clok** [now-ims/hapi-now-auth#17]
The `joi` project is no longer maintained within the Hapi project. It is now in its own namespace. https://joi.dev/

As a result, when using hapi v20+ you must include both `@hapi/joi` (which is stale) and `joi` in your project dependencies to get `@now-ims/hapi-auth-now` to work. The project doesn't appear to list `@hapi/joi` as a dependency and this has led to build failures and workarounds.

**Comment by puchesjr** [comment]
We apologize for this issue and will update the package to use the appropriate dependencies

**Comment by clok** [comment]
Thank you!
