### ISSUE TITLE
h.unauthorized isn't a function

### ISSUE THREAD

**Issue by marcuspoehls** [now-ims/hapi-now-auth#3]
If returned `credentials` from the `validate` function aren't set or aren't an object, [you're throwing `h.unauthorized` with `Boom.badImplementation`](https://github.com/now-ims/hapi-now-auth/blob/master/lib/index.js#L137). `h.unauthorized` isn't a function on hapi's `h` tookit. 

I guess you should just throw the error and let hapi return it as a response

**Comment by puchesjr** [comment]
@marcuspoehls apologize for that. I'll look into this now, I was creating this plugin as hapi was in the middle of the new version.  I will resolve this by by the end of the day.

**Comment by marcuspoehls** [comment]
@puchesjr No worries. I just came across the problem when returning the wrong value from the validation function

Thank you for looking into this!

**Comment by puchesjr** [comment]
This is resolved with the latest patch update.
