### ISSUE TITLE
Explicit "Token expired" error message

### ISSUE THREAD

**Issue by marcuspoehls** [now-ims/hapi-now-auth#7]
Hey friends,

thank you for your recent changes on `hapi-now-auth` and passing through error messages.

Is there a chance the explicitly know if a token is expired?
I’d like to tell users that they have to renew the token. The current error message is this: `Invalid JWT: key or signature is invalid`.

The current error message is correct. I’m just looking for a detailed error message besides the general "is invalid" for expired tokens.

Do you think there’s a chance to add that?

**Comment by puchesjr** [comment]
@marcuspoehls this shouldn't be an issue at all. Give me a little bit of time and I'll return token expiration
