### ISSUE TITLE
Add JWT Signing

### ISSUE THREAD

**Issue by puchesjr** [now-ims/hapi-now-auth#8]
Would you like to see JWT Signing from this plugin?

Why or why not?

**Comment by thefoxie** [comment]
@puchesjr what's the conclusion? I guess it won't be implemented since the question was like 2y ago. Another good feature would be token blacklisting/logout.

**Comment by puchesjr** [comment]
We are currently migrating this to Typescript and will add the ability to generate JWTs.  Not sure how we would handle the blacklisting/logout, to be honest.  How would you like to see the blacklisting/logout working in this package?
